project_id = "jkmiemvihdjwpcpgfleh"

[functions.send-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.cron-import]
verify_jwt = false

[functions.integration-sdk]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false
